# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.401.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.24.6
  tags:
  - golang
- name: golangci/golangci-lint@v2.3.1
- name: goreleaser/goreleaser@v2.11.2
- name: securego/gosec@v2.22.7
- name: reviewdog/reviewdog@v0.20.3
- name: mvdan/sh@v3.12.0
- name: koalaman/shellcheck@v0.11.0
- name: rhysd/actionlint@v1.7.7
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.65.0
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.4.0
- name: google/yamlfmt@v0.17.2
