# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.474.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.26.0
  tags:
  - golang
- name: golangci/golangci-lint@v2.10.1
- name: goreleaser/goreleaser@v2.14.0
- name: securego/gosec@v2.23.0
- name: reviewdog/reviewdog@v0.21.0
- name: mvdan/sh@v3.12.0
- name: koalaman/shellcheck@v0.11.0
- name: rhysd/actionlint@v1.7.11
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.69.1
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.6.1
- name: google/yamlfmt@v0.21.0
