# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.155.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: dominikh/go-tools/staticcheck@2023.1.7
- name: goreleaser/goreleaser@v1.24.0
- name: securego/gosec@v2.19.0
- name: reviewdog/reviewdog@v0.17.2
- name: mvdan/sh@v3.8.0
- name: koalaman/shellcheck@v0.10.0
- name: rhysd/actionlint@v1.6.27
- name: rust-lang/mdBook@v0.4.37
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.50.1
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.0.0
