# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.80.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: dominikh/go-tools/staticcheck@2023.1.6
- name: goreleaser/goreleaser@v1.22.0
- name: securego/gosec@v2.18.2
- name: reviewdog/reviewdog@v0.15.0
- name: mvdan/sh@v3.7.0
- name: koalaman/shellcheck@v0.9.0
- name: rhysd/actionlint@v1.6.26
- name: rust-lang/mdBook@v0.4.35
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.47.0
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@2.7.2
