# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.391.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.24.5
  tags:
  - golang
- name: golangci/golangci-lint@v2.3.0
- name: goreleaser/goreleaser@v2.11.0
- name: securego/gosec@v2.22.7
- name: reviewdog/reviewdog@v0.20.3
- name: mvdan/sh@v3.12.0
- name: koalaman/shellcheck@v0.10.0
- name: rhysd/actionlint@v1.7.7
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.64.1
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.3.0
- name: google/yamlfmt@v0.17.2
