# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.200.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: dominikh/go-tools/staticcheck@2023.1.7
- name: goreleaser/goreleaser@v2.0.1
- name: securego/gosec@v2.20.0
- name: reviewdog/reviewdog@v0.18.1
- name: mvdan/sh@v3.8.0
- name: koalaman/shellcheck@v0.10.0
- name: rhysd/actionlint@v1.7.1
- name: rust-lang/mdBook@v0.4.40
- name: takumin/gjson@v0.0.2
- name: aquasecurity/trivy@v0.52.2
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.0.1
