# https://rust-lang.github.io/mdBook/

[book]
title = "gyaml"
description = "Golang YAML Tool"
authors = ["takumin"]
src = "docs"
language = "ja"
multilingual = false

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/takumin/gyaml"
