name: Reviewdog (gjson-validate)
on:
  workflow_call:
    inputs:
      jobname:
        type: string
        required: false
        description: 'A jobname passed from the caller workflow'
        default: 'reviewdog-gjson-validate'
  pull_request:
    paths:
    - '.github/actions/setup-reviewdog/action.yaml'
    - '.github/workflows/reviewdog-gjson-validate.yml'
    - '.aqua.yaml'
    - '.reviewdog.yml'
    - '**.json'
    - '**.json.golden'
    - '!**.invalid.json.golden'
permissions:
  checks: write
  contents: read
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || inputs.jobname }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.53.9
        aqua_opts: --exclude-tags golang
    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod
        cache: false
    - name: Setup Reviewdog
      id: reviewdog
      uses: ./.github/actions/setup-reviewdog
    - name: Reviewdog
      run: reviewdog -runners 'gjson-validate' -reporter '${{ steps.reviewdog.outputs.reporter }}' -diff 'git diff FETCH_HEAD' -fail-on-error
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
